### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by Alexandria** [Alexandria/match-three-game#20]
There really is no  accessibility considerations on this project. It would be nice to hover over each candy and have a screen reader read the color and shape. Im not sure if this is possible but at the very least it would be worth looking into.

**Comment by lizwait** [comment]
Hey Lex! I'll take a shot at it! :) This game is so cute!

**Comment by Alexandria** [comment]
Awesome, its yours!

**Comment by Alexandria** [comment]
Closing because this is too vague of an issue. Will work on a few more specific issues for accessibility latter
