### ISSUE TITLE
Show a replay prompt when the game ended.

### ISSUE THREAD

**Issue by Alexandria** [Alexandria/match-three-game#33]
Right now the game just ends when the timer runs out.
Lets get a prompt that pops up when the game is over so that the player can just click "replay" ( or something similar ) and the game will start over.

**Comment by Alexandria** [comment]
> Yeah, ill nab it. Any special instructions for getting it to run on local?

If you are using chrome you can actually drag and drop the HTML file into your browser and it will run it there.

**Comment by suhhee1011** [comment]
Hi @Alexandria, I created pull request for this issue. 
Please review my pull request :)
