### ISSUE TITLE
Link from CONTRIBUTING.md goes to incorrect page

### ISSUE THREAD

**Issue by j-kincaid** [Alexandria/match-three-game#47]
**The Bug:**

On CONTRIBUTING.md, in the Final notes section, the link named **issue** takes the user to the actual game, not the Issues page.

**To Reproduce**
1. Go to 'CONTRIBUTING.md'
2. Scroll down to 'Final notes'
3. Click on 'issue' link
4. The user goes to the page where they can play the game.

**Expected behavior**
The user goes to the Issues list.

**Comment by Jisan129** [comment]
Can I try this?

**Comment by Alexandria** [comment]
Its yours!
