### ISSUE TITLE
candy pieces are sticky when they should be movable

### ISSUE THREAD

**Issue by j-kincaid** [Alexandria/match-three-game#65]
**Describe the bug**

This happens more in the lower right area of the board: When playing the game with the timer running, etc., I can only slide a candy in the direction that creates a match of three. The user should be able to make a wrong move. 

**To Reproduce**
1. Click on the start button.
2. When playing the game, try to click, hold and drag a candy to where is does **not** align three matching candies in a row.
3. Notice how it feels like your mouse is stuck, or the candy doesn't move.
4. This occurs more often on the right side of the board.

**Expected behavior**
The user can make a disadvantageous move by dragging a candy to a space where it does not add to the score.

**Comment by suhhee1011** [comment]
@Alexandria Can I work on this too?

**Comment by Alexandria** [comment]
Its yours!
