### ISSUE TITLE
No cursor pointer when hovering over the play button or hovering over the candies

### ISSUE THREAD

**Issue by rsinghcodes** [Alexandria/match-three-game#66]
**Describe the bug**
Whenever I'm hovering over the play button and hovering over the candies, I don't feel like the button is clickable or the candies are draggable.

**Expected behavior**
There should be cursor pointer on the play button and the cursor pointer should also be there when hovering over the candy to get the feel that the button is clickable and that the candies are draggable.

**Comment by Alexandria** [comment]
Thanks for reporting this. Can you send screenshots? I am trying to recreate this bug but am having trouble doing so.

**Comment by rsinghcodes** [comment]
> Thanks for reporting this. Can you send screenshots? I am trying to recreate this bug but am having trouble doing so.

### Bug Screenshot 👇

![Bug Screenshot](https://user-images.githubusercontent.com/67682451/139522811-f97dc766-52d1-42f2-81d7-376c2af927c9.png)

![Bug Screenshot 1](https://user-images.githubusercontent.com/67682451/139522761-5e61006d-29d6-4fd4-8f29-45f5e207ec70.png)
